<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <TargetFramework>net8.0-windows10.0.17763</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <RootNamespace>SoftPhone</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SoftPhone</AssemblyName>
    <AssemblyTitle>SoftPhone</AssemblyTitle>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="10.0.3" />
    <PackageReference Include="SIPSorceryMedia.Windows" Version="8.0.14" />
  </ItemGroup>

</Project>
